/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexsimulazioneatletica;

/**
 *
 * @author goretti.leonardo
 */
public class FRMAtleti extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMAtleti.class.getName());

    /**
     * Creates new form FRMAtleti
     */
    public FRMAtleti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLNome = new javax.swing.JLabel();
        LBLCognome = new javax.swing.JLabel();
        LBLNumero = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        TXTCognome = new javax.swing.JTextField();
        TXTNumero = new javax.swing.JTextField();
        BTNInviaAtleta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTListaAtleti = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iscrizione atleti");
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        LBLNome.setText("Inserisci nome:");
        getContentPane().add(LBLNome);
        LBLNome.setBounds(30, 110, 100, 16);

        LBLCognome.setText("Inserisci cognome:");
        getContentPane().add(LBLCognome);
        LBLCognome.setBounds(30, 140, 100, 16);

        LBLNumero.setText("Inserisci numero:");
        getContentPane().add(LBLNumero);
        LBLNumero.setBounds(30, 170, 100, 16);
        getContentPane().add(TXTNome);
        TXTNome.setBounds(160, 100, 80, 26);
        getContentPane().add(TXTCognome);
        TXTCognome.setBounds(160, 130, 80, 26);
        getContentPane().add(TXTNumero);
        TXTNumero.setBounds(160, 160, 80, 26);

        BTNInviaAtleta.setText("Invia atleta");
        getContentPane().add(BTNInviaAtleta);
        BTNInviaAtleta.setBounds(280, 130, 110, 27);

        TXTListaAtleti.setColumns(20);
        TXTListaAtleti.setRows(5);
        jScrollPane1.setViewportView(TXTListaAtleti);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 10, 360, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMAtleti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNInviaAtleta;
    private javax.swing.JLabel LBLCognome;
    private javax.swing.JLabel LBLNome;
    private javax.swing.JLabel LBLNumero;
    private javax.swing.JTextField TXTCognome;
    private javax.swing.JTextArea TXTListaAtleti;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JTextField TXTNumero;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
