/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexsimulazioneatletica;

/**
 *
 * @author goretti.leonardo
 */
public class FRMGara extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMGara.class.getName());

    /**
     * Creates new form FRMGara
     */
    public FRMGara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LSTGare = new javax.swing.JList<>();
        LBLInserisciGara = new javax.swing.JLabel();
        TXTInserisciGara = new javax.swing.JTextField();
        BTNInviaGara = new javax.swing.JButton();
        LBLNumGiocatori = new javax.swing.JLabel();
        TXTNumAtleti = new javax.swing.JTextField();
        BTNnumAtleti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestione gara");
        setMinimumSize(new java.awt.Dimension(800, 300));
        getContentPane().setLayout(null);

        LSTGare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LSTGare.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista gare:", "Atletica 100m", "Lancio del peso", "Salto in lungo", "Lancio del giavellotto", "Maratona" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        getContentPane().add(LSTGare);
        LSTGare.setBounds(26, 17, 207, 110);

        LBLInserisciGara.setText("Inserisci gara:");
        getContentPane().add(LBLInserisciGara);
        LBLInserisciGara.setBounds(251, 19, 71, 16);
        getContentPane().add(TXTInserisciGara);
        TXTInserisciGara.setBounds(340, 10, 158, 26);

        BTNInviaGara.setText("Invia Gara");
        getContentPane().add(BTNInviaGara);
        BTNInviaGara.setBounds(510, 10, 86, 27);

        LBLNumGiocatori.setText("Inserisci numero atleti:");
        getContentPane().add(LBLNumGiocatori);
        LBLNumGiocatori.setBounds(250, 110, 120, 16);
        getContentPane().add(TXTNumAtleti);
        TXTNumAtleti.setBounds(380, 100, 158, 26);

        BTNnumAtleti.setText("Invia Atleti");
        getContentPane().add(BTNnumAtleti);
        BTNnumAtleti.setBounds(550, 100, 90, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMGara().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNInviaGara;
    private javax.swing.JButton BTNnumAtleti;
    private javax.swing.JLabel LBLInserisciGara;
    private javax.swing.JLabel LBLNumGiocatori;
    private javax.swing.JList<String> LSTGare;
    private javax.swing.JTextField TXTInserisciGara;
    private javax.swing.JTextField TXTNumAtleti;
    // End of variables declaration//GEN-END:variables
}
