/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexsimulazioneatletica;

import java.awt.HeadlessException;
import java.util.ArrayList;

/**
 *
 * @author goretti.leonardo
 */
public class FRMGara extends javax.swing.JFrame {

    /**
     * Creates new form FRMGara
     */
    public FRMGara() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LSTGare = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        txtDurata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCreaGara = new javax.swing.JButton();
        btnClassifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestione gara");
        setMinimumSize(new java.awt.Dimension(800, 300));

        LSTGare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LSTGare.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista gare:", "Atletica 100m", "Lancio del peso", "Salto in lungo", "Lancio del giavellotto", "Maratona" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LSTGare.setEnabled(false);
        getContentPane().add(LSTGare, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Simulatore meeting atletica");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Seleziona tipo di gara");

        cbTipo.setMaximumRowCount(5);
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleziona ", "Atletica 100m", "Lancio del peso", "Salto in lungo", "Lancio del giavellotto", "Maratona" }));
        cbTipo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        cbTipo.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel3.setText("Inserire la durata (h,min,sec)");

        btnCreaGara.setText("Invia");
        btnCreaGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaGaraActionPerformed(evt);
            }
        });

        btnClassifica.setText("Classifica");
        btnClassifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDurata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnClassifica)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(61, 61, 61)
                .addComponent(btnCreaGara, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDurata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreaGara, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(btnClassifica)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreaGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaGaraActionPerformed
        try {
            if("Seleziona ".equals(cbTipo.getSelectedItem().toString())){
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Scegli un tipo di gara valido",
                        "Attenzione",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtDurata.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Inserisci un valore per la durata!",
                        "Attenzione",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return; // Esce dal metodo senza fare nulla
            }
            if (cbTipo.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Seleziona un tipo di gara!",
                        "Attenzione",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            float durata = Float.parseFloat(txtDurata.getText());
            String tipo = cbTipo.getSelectedItem().toString();
            m.creaGara(durata, tipo);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gara creata con successo!",
                    "Info",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            for(Gara g : m.getListaGare()){
                g.svolgiGara();
            }
            
            // Aggiorna la classifica con i dati della nuova gara
            aggiornaClassifica();
            
        } catch (NumberFormatException e) {
            // SCATTA SE: L'utente scrive "abc" o "12,5" (con virgola invece di punto)
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Errore: La durata deve essere un numero valido (usa il punto per i decimali).",
                    "Errore di Formato",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } catch (HeadlessException e) {
            // SCATTA SE: C'è un errore generico non previsto
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Si è verificato un errore imprevisto: " + e.getMessage(),
                    "Errore",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCreaGaraActionPerformed

    private void btnClassificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificaActionPerformed
         FRMClassifica finestra = new FRMClassifica();
         finestra.setClassifica(generaTestoClassifica());
         finestra.setVisible(true);
    }//GEN-LAST:event_btnClassificaActionPerformed
    
    /**
     * Metodo per generare il testo della classifica con tutti i dati delle gare
     */
    private String generaTestoClassifica() {
        StringBuilder sb = new StringBuilder();
        sb.append("=".repeat(80)).append("\n");
        sb.append("CLASSIFICA GENERALE DEL MEETING\n");
        sb.append("=".repeat(80)).append("\n\n");
        
        if (m.getListaGare().isEmpty()) {
            sb.append("Nessuna gara creata ancora.\n");
        } else {
            for (int i = 0; i < m.getListaGare().size(); i++) {
                Gara g = m.getListaGare().get(i);
                sb.append("GARA ").append(i + 1).append("\n");
                sb.append("-".repeat(80)).append("\n");
                sb.append("Tipologia: ").append(g.getTipologia()).append("\n");
                sb.append("Durata: ").append(g.getDurata()).append(" ore\n\n");
                
                // Ordina gli atleti per punteggio (crescente, minore è meglio)
                ArrayList<Atleta> atleti = new ArrayList<>(g.getListaAtleti());
                atleti.sort((a1, a2) -> Double.compare(a1.calcolaPunteggio(), a2.calcolaPunteggio()));
                
                sb.append("CLASSIFICA ATLETI:\n");
                int posizione = 1;
                for (Atleta a : atleti) {
                    double punteggio = a.calcolaPunteggio();
                    String nome = a.getNome();
                    String cognome = a.getCognome();
                    
                    if (a.equals(g.getVincitore())) {
                        sb.append("🥇 ").append(posizione).append(". ")
                          .append(nome).append(" ").append(cognome)
                          .append(" - Punteggio: ").append(String.format("%.2f", punteggio))
                          .append(" (VINCITORE)\n");
                    } else {
                        sb.append("   ").append(posizione).append(". ")
                          .append(nome).append(" ").append(cognome)
                          .append(" - Punteggio: ").append(String.format("%.2f", punteggio)).append("\n");
                    }
                    posizione++;
                }
                sb.append("\n");
            }
        }
        sb.append("=".repeat(80)).append("\n");
        return sb.toString();
    }
    
    /**
     * Metodo per aggiornare la classifica dopo la creazione di una gara
     */
    private void aggiornaClassifica() {
        synchronized (this) {
            // Se la finestra della classifica è già aperta, aggiornala
            // Altrimenti, il testo sarà disponibile quando l'utente apre la classifica
        }
    }

    Meeting m = new Meeting();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LSTGare;
    private javax.swing.JButton btnClassifica;
    private javax.swing.JButton btnCreaGara;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDurata;
    // End of variables declaration//GEN-END:variables
}
